// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDImWX0R6h7yX99hjJuB31Rh0yx5gXJP94',
    appId: '1:321842294164:web:86f43834b444816b0a3381',
    messagingSenderId: '321842294164',
    projectId: 'fir-dbbd2',
    authDomain: 'fir-dbbd2.firebaseapp.com',
    storageBucket: 'fir-dbbd2.firebasestorage.app',
    measurementId: 'G-X41SXPY4ZC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClrjoPBZ1tOegQcHP7O8ifcVRXzcDdnUE',
    appId: '1:321842294164:android:18f8e051173247980a3381',
    messagingSenderId: '321842294164',
    projectId: 'fir-dbbd2',
    storageBucket: 'fir-dbbd2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCErU0iE0vP-wV1f926Qypx7QEb0hSNlK4',
    appId: '1:321842294164:ios:0d61799a5ba7e86b0a3381',
    messagingSenderId: '321842294164',
    projectId: 'fir-dbbd2',
    storageBucket: 'fir-dbbd2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCErU0iE0vP-wV1f926Qypx7QEb0hSNlK4',
    appId: '1:321842294164:ios:0d61799a5ba7e86b0a3381',
    messagingSenderId: '321842294164',
    projectId: 'fir-dbbd2',
    storageBucket: 'fir-dbbd2.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDImWX0R6h7yX99hjJuB31Rh0yx5gXJP94',
    appId: '1:321842294164:web:6a4bab34ef9d06900a3381',
    messagingSenderId: '321842294164',
    projectId: 'fir-dbbd2',
    authDomain: 'fir-dbbd2.firebaseapp.com',
    storageBucket: 'fir-dbbd2.firebasestorage.app',
    measurementId: 'G-1R1HN5KNYV',
  );
}
